version: "3"

services:

  web:
    command: bash ./scripts/development.sh
    volumes:
      - ".:/app"
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.development
