# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

POST http://{{host}}:{{port}}/api/posts/
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "Create post",
  "description": "Post description."
}

###

POST http://{{host}}:{{port}}/api/posts/1/like/
Content-Type: application/json
Authorization: Bearer {{token}}

{}

###

POST http://{{host}}:{{port}}/api/posts/1/unlike/
Content-Type: application/json
Authorization: Bearer {{token}}

{}

###

POST http://{{host}}:{{port}}/api/posts/1/delete_reaction/
Content-Type: application/json
Authorization: Bearer {{token}}

{}

###
